---
#
# Ansible managed
#
repository:
  description: Install, start and enable sysstat on your system.
  homepage: https://robertdebock.nl/
  topics: sysstat, monitoring, system, security, ansible, molecule, playbook
